"""Send the dengue report via email with a color-coded HTML status table and PDF attachment."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import ClassVar

from acestor import BaseStep, PipelineContext
from acestor.infra.email import send_email
from pipelines.dengue.results import ReportResult, SendReportResult

_STATUS_STYLE = {
    "Success": ("bg:#e6f4ea", "color:#1e7e34", "✓"),
    "Warning": ("bg:#fff8e1", "color:#e65100", "⚠"),
    "Note": ("bg:#e8f0fe", "color:#1a56db", "ℹ"),
    "Error": ("bg:#fdecea", "color:#b71c1c", "✗"),
    "Critical": ("bg:#fdecea", "color:#7f0000", "✗"),
}


def _fix_date(value: str) -> str:
    """Strip LaTeX double-dash encoding from dates (2026--03--18 → 2026-03-18)."""
    return value.replace("--", "-")


def _build_html(
    title: str,
    rows: list[tuple[str, str, str]],
    timestamp: str,
    pipeline_name: str = "Dengue",
) -> str:
    row_html = ""
    for i, (component, status, detail) in enumerate(rows):
        bg, fg, icon = _STATUS_STYLE.get(status, ("bg:#fff", "color:#333", "•"))
        bg_color = bg[3:]  # strip "bg:" prefix
        row_bg = "#ffffff" if i % 2 == 0 else "#f9f9f9"
        row_html += f"""
        <tr style="background:{row_bg}">
          <td style="padding:12px 16px;border-bottom:1px solid #e0e0e0;font-weight:500;color:#333;font-size:14px">{component}</td>
          <td style="padding:12px 16px;border-bottom:1px solid #e0e0e0;font-size:14px">
            <span style="display:inline-block;padding:3px 10px;border-radius:12px;background:{bg_color};{fg};font-size:13px;font-weight:600">{icon} {status}</span>
          </td>
          <td style="padding:12px 16px;border-bottom:1px solid #e0e0e0;color:#555;font-size:14px">{detail}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif">
  <div style="max-width:700px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1)">

    <!-- Header -->
    <div style="background:#1a3c5e;padding:24px 32px">
      <div style="font-size:11px;color:#90b8d8;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px">{pipeline_name.title()} Pipeline</div>
      <div style="font-size:22px;font-weight:700;color:#ffffff">{title}</div>
    </div>

    <!-- Table -->
    <div style="padding:0">
      <table style="width:100%;border-collapse:collapse">
        <thead>
          <tr style="background:#f0f4f8">
            <th style="padding:12px 16px;text-align:left;font-size:12px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #dde3ea">Component</th>
            <th style="padding:12px 16px;text-align:left;font-size:12px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #dde3ea">Status</th>
            <th style="padding:12px 16px;text-align:left;font-size:12px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #dde3ea">Details</th>
          </tr>
        </thead>
        <tbody>{row_html}
        </tbody>
      </table>
    </div>

    <!-- Footer -->
    <div style="padding:16px 32px;background:#f8f9fa;border-top:1px solid #e0e0e0;text-align:right">
      <span style="font-size:12px;color:#999">Generated by acestor &middot; {timestamp}</span>
    </div>

  </div>
</body>
</html>"""


@dataclass(frozen=True)
class SendReportInputs:
    generate_report: ReportResult


class SendReportStep(BaseStep[SendReportInputs, SendReportResult]):
    input_type: ClassVar[type] = SendReportInputs

    def run(
        self, context: PipelineContext, inputs: SendReportInputs
    ) -> SendReportResult:
        cfg = context.config or {}
        email_cfg = cfg.get("email") or {}

        context.log.info("send_report: email.enabled=%s", email_cfg.get("enabled"))

        if not email_cfg.get("enabled"):
            context.log.info("send_report: email disabled in config — skipping")
            return SendReportResult(sent=False, reason="disabled")

        if "success" not in (email_cfg.get("on") or []):
            context.log.info("send_report: 'success' not in email.on — skipping")
            return SendReportResult(sent=False, reason="not_subscribed")

        smtp_cfg = email_cfg.get("smtp") or {}
        host = smtp_cfg.get("host")
        port = int(smtp_cfg.get("port", 587))
        username = smtp_cfg.get("username")
        password = smtp_cfg.get("password")
        use_tls = bool(smtp_cfg.get("use_tls", True))
        sender = email_cfg.get("from")
        recipients = email_cfg.get("to") or []

        context.log.info(
            "send_report: host=%s port=%s sender=%s recipients=%s",
            host,
            port,
            sender,
            recipients,
        )

        if not host or not sender or not recipients:
            context.log.warning(
                "send_report: email enabled but missing host/from/to — skipping"
            )
            return SendReportResult(sent=False, reason="smtp_incomplete")

        # Read rep_dict for report metadata
        rep_dict: dict = {}
        try:
            raw = context.artifacts.read_text(inputs.generate_report.report_path)
            rep_dict = json.loads(raw)
        except Exception as e:
            context.log.warning("send_report: could not read rep_dict JSON: %s", e)

        reportmonth = rep_dict.get("reportmonth") or "—"
        prediction_date = _fix_date(rep_dict.get("prediction_date") or "—")
        epi_start = _fix_date(rep_dict.get("epi_data_start_date") or "—")
        epi_end = _fix_date(rep_dict.get("epi_data_end_date") or "—")
        weather_end = _fix_date(rep_dict.get("weather_data_end_date") or "—")

        pipeline_name = (cfg.get("pipeline") or {}).get("name") or "dengue"
        run_date = datetime.now(timezone.utc).strftime("%Y%m%d")
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        rows: list[tuple[str, str, str]] = [
            ("Case Data", "Success", f"Epi data from {epi_start} to {epi_end}"),
            ("Weather Data", "Success", f"Weather data through {weather_end}"),
            (
                "Predictions",
                "Success",
                f"Prediction date: {prediction_date} | Report period: {reportmonth}",
            ),
        ]

        report_path = inputs.generate_report.report_path
        rows.append(
            ("Report", "Success", "HTML report ready")
            if report_path
            else ("Report", "Warning", "No report generated for this run")
        )

        subject = f"{pipeline_name.title()} Pipeline | {reportmonth} | {run_date}"
        plain = "\n".join(f"{c}: [{s}] {d}" for c, s, d in rows)
        html = _build_html(
            title=f"Pipeline Report — {reportmonth}",
            rows=rows,
            timestamp=timestamp,
            pipeline_name=pipeline_name,
        )

        attachments = []
        if report_path and Path(report_path).exists():
            attachments.append(report_path)

        try:
            send_email(
                host=host,
                port=port,
                username=username,
                password=password,
                use_tls=use_tls,
                sender=sender,
                recipients=recipients,
                subject=subject,
                body=plain,
                html_body=html,
                attachments=attachments,
            )
            context.log.info(
                "send_report: sent to %d recipients, %d attachment(s)",
                len(recipients),
                len(attachments),
            )
            return SendReportResult(sent=True, reason="sent")
        except Exception as exc:
            import traceback

            context.log.error("send_report: failed to send email: %s", exc)
            context.log.error(traceback.format_exc())
            return SendReportResult(sent=False, reason=f"send_failed: {exc}")
