[project]
name = "acestor"
version = "0.1.0"
description = "Package to run different disease models"
authors = [
    {name = "Tarun Khandelwal", email = "tarun@artpark.in"},
    {name = "Sai Sneha", email = "sneha@artpark.in"},
    {name = "Akhil Babu", email = "akhil@artpark.in"}
]
readme = "README.md"
requires-python = ">=3.12"
license = {text = "GPL-3.0"}

dependencies = [
    "anthropic>=0.68.0",
    "boto3>=1.39.17",
    "cdsapi>=0.7.6",
    "dataio-artpark",
    "geopandas>=1.1.1",
    "indra",
    "ipykernel>=7.0.0",
    "matplotlib>=3.10.3",
    "netcdf4>=1.7.3",
    "numpy>=2.3.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "pdf2image>=1.17.0",
    "pillow>=11.2.1",
    "psutil>=7.1.0",
    "pylatex>=1.4.2",
    "python-dotenv>=1.1.1",
    "python-magic>=0.4.27",
    "pyyaml>=6.0.2",
    "ruff>=0.13.1",
    "scikit-learn>=1.7.0",
    "shapely>=2.1.1",
    "statsmodels>=0.14.5",
    "tqdm>=4.67.1",
    "typer>=0.15.2",
    "typing>=3.10.0.0",
    "xarray>=2025.6.1",
    "xlwings>=0.33.16",
]

[tool.ruff]
line-length = 140
target-version = "py312"
select = ["E", "F", "W", "I", "FLY", "RUF", "B", "ICN"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.isort]
known-first-party = ["patchsim"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=9.3.0",
]
docs = [
    "sphinx>=8.0.0",
    "furo>=2024.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/acestor"]

[tool.uv.sources]
dataio-artpark = { git = "https://github.com/dsih-artpark/dataio.git", rev = "staging" }
indra = { git = "https://github.com/dsih-artpark/indra.git", rev = "production" }
