"""Send the dengue report via email with a color-coded HTML status table and PDF attachment."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import ClassVar

from acestor import BaseStep, PipelineContext
from acestor.infra.email import send_email
from pipelines.gba_dengue.results import ReportResult, SendReportResult

# (component, status, color) — matches existing pipeline palette
_COLORS = {
    "Success": "green",
    "Warning": "orange",
    "Note": "steelblue",
    "Error": "darkred",
    "Critical": "red",
}

_TH = "style='border:1px solid black;font-size:18px;padding:10px;background:#f2f2f2;text-align:left'"
_TD = "style='border:1px solid black;padding:10px;font-size:16px'"


def _build_html(title: str, rows: list[tuple[str, str, str]], timestamp: str) -> str:
    header = "".join(f"<th {_TH}>{h}</th>" for h in ["Component", "Status", "Details"])
    body_rows = ""
    for component, status, detail in rows:
        color = _COLORS.get(status, "black")
        body_rows += (
            f"<tr style='color:{color}'>"
            f"<td {_TD}>{component}</td>"
            f"<td {_TD}>{status}</td>"
            f"<td {_TD}>{detail}</td>"
            f"</tr>"
        )
    return f"""<html><body style='font-family:Arial,sans-serif;padding:20px'>
<h2 style='color:#333'>{title}</h2>
<table style='border-collapse:collapse;border:1px solid black;width:100%'>
<tr>{header}</tr>
{body_rows}
</table>
<p style='color:#999;font-size:12px;margin-top:20px'>
  Generated by acestor pipeline &middot; {timestamp}
</p>
</body></html>"""


@dataclass(frozen=True)
class SendReportInputs:
    generate_report: ReportResult


class SendReportStep(BaseStep[SendReportInputs, SendReportResult]):
    input_type: ClassVar[type] = SendReportInputs

    def run(
        self, context: PipelineContext, inputs: SendReportInputs
    ) -> SendReportResult:
        cfg = context.config if isinstance(context.config, dict) else {}
        email_cfg = cfg.get("email") if isinstance(cfg.get("email"), dict) else {}

        if not email_cfg.get("enabled"):
            return SendReportResult(sent=False, reason="disabled")

        if "success" not in (email_cfg.get("on") or []):
            return SendReportResult(sent=False, reason="not_subscribed")

        smtp_cfg = email_cfg.get("smtp") or {}
        host = smtp_cfg.get("host")
        port = int(smtp_cfg.get("port", 587))
        username = smtp_cfg.get("username")
        password = smtp_cfg.get("password")
        use_tls = bool(smtp_cfg.get("use_tls", True))
        sender = email_cfg.get("from")
        recipients = email_cfg.get("to") or []

        if not host or not sender or not recipients:
            context.log.warning(
                "send_report: email enabled but missing host/from/to — skipping"
            )
            return SendReportResult(sent=False, reason="smtp_incomplete")

        # Read rep_dict for report metadata
        rep_dict: dict = {}
        try:
            raw = context.artifacts.read_text(inputs.generate_report.report_path)
            rep_dict = json.loads(raw)
        except Exception:
            context.log.warning("send_report: could not read rep_dict JSON")

        reportmonth = rep_dict.get("reportmonth") or "—"
        prediction_date = rep_dict.get("prediction_date") or "—"
        epi_start = rep_dict.get("epi_data_start_date") or "—"
        epi_end = rep_dict.get("epi_data_end_date") or "—"
        weather_end = rep_dict.get("weather_data_end_date") or "—"

        pipeline_name = (cfg.get("pipeline") or {}).get("name") or "dengue"
        run_date = datetime.now(timezone.utc).strftime("%Y%m%d")
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        rows: list[tuple[str, str, str]] = [
            ("Case Data", "Success", f"Epi data from {epi_start} to {epi_end}"),
            ("Weather Data", "Success", f"Weather data through {weather_end}"),
            (
                "Predictions",
                "Success",
                f"Prediction date: {prediction_date} | Report period: {reportmonth}",
            ),
        ]

        maps_zip = inputs.generate_report.maps_zip_path
        rows.append(
            ("Map Generation", "Success", f"Maps zip: {Path(maps_zip).name}")
            if maps_zip
            else ("Map Generation", "Note", "No maps generated for this run")
        )

        pdf_path = inputs.generate_report.pdf_path
        rows.append(
            ("Report", "Success", f"PDF report compiled: {Path(pdf_path).name}")
            if pdf_path
            else (
                "Report",
                "Warning",
                "LaTeX sources available — PDF compilation skipped or failed",
            )
        )

        subject = f"{pipeline_name.title()} Pipeline | {reportmonth} | {run_date}"
        plain = "\n".join(f"{c}: [{s}] {d}" for c, s, d in rows)
        html = _build_html(
            title=f"Pipeline Report — {reportmonth}",
            rows=rows,
            timestamp=timestamp,
        )

        attachments = []
        if pdf_path and Path(pdf_path).exists():
            attachments.append(pdf_path)
        if maps_zip and Path(maps_zip).exists():
            attachments.append(maps_zip)

        try:
            send_email(
                host=host,
                port=port,
                username=username,
                password=password,
                use_tls=use_tls,
                sender=sender,
                recipients=recipients,
                subject=subject,
                body=plain,
                html_body=html,
                attachments=attachments,
            )
            context.log.info(
                "send_report: sent to %d recipients, %d attachment(s)",
                len(recipients),
                len(attachments),
            )
            return SendReportResult(sent=True, reason="sent")
        except Exception as exc:
            context.log.exception("send_report: failed to send email")
            return SendReportResult(sent=False, reason=f"send_failed: {exc}")
